### ISSUE TITLE
Consumable Resource Changes

### ISSUE THREAD

**Issue by landon912** [lancium/GenesisII#22]
As previously discussed, slurm is currently:

1) Using Cores instead of CPUs to schedule
2) Not using memory as a consumable resource

Proposed changes are:
1) Change slurm to use CPUs instead of Cores
2) Enable memory as a consumable resource
    i) Default memory requirement has now been set to 4GB in a previous commit to prepare for this change.

**Comment by ag8t** [comment]
Done with the cgroups upgrade to the production system.
