### ISSUE TITLE
VM External Termination

### ISSUE THREAD

**Issue by ag8t** [lancium/GenesisII#32]
Currently there is no way to terminate a VM externally except having one of us shell on to the machine and virsh destroy it.

We need to:
1. When the ProcessWrapper is told to shutdown (either by a signal) or later by a message from the BES, signal the vmWrapper to shutdown.
2. Have the vmWrapper catch the signal, do a virsh destroy. Later we might write a nonce to a port on the VM telling it we are about to shut them down.
Clearly if/when we incorporate the vmWrapper and singularityWrapper into the processWrapper we will not have to do this anymore.

**Comment by landon912** [comment]
Fix for GPU VMs in 231c78a and lancium/start_vm@ab43c1f.
